-- 인기 프리셋 초기 데이터 (벤치마크 ETF인 SPY/QQQ/VOO 제외 — 비교 대상만 포함)
INSERT OR IGNORE INTO preset (name, description, tickers, sort_order) VALUES
  ('레버리지 ETF 비교', 'S&P 500 레버리지 ETF vs 지수 비교', '["SSO","UPRO","SPXL"]', 1),
  ('나스닥 레버리지', 'NASDAQ 100 레버리지 ETF vs 지수 비교', '["QLD","TQQQ"]', 2),
  ('섹터 ETF 비교', '주요 섹터 ETF vs S&P 500 비교', '["XLK","XLV","XLF"]', 3),
  ('배당 ETF 비교', '고배당 ETF vs S&P 500 비교', '["VYM","SCHD","DVY"]', 4),
  ('채권혼합 ETF', '자산배분 ETF vs 지수 비교', '["AOM","AOR","AOA"]', 5),
  ('성장주 ETF', '성장주 ETF vs NASDAQ 100 비교', '["VUG","MGK","IWF"]', 6);

-- 성과비교 대상 ETF 목록 (미국 상장 시가총액 상위 30개, 유럽 제외)
INSERT OR IGNORE INTO ranking_etf (ticker, name, category, is_active, sort_order) VALUES
  ('VOO',  'Vanguard S&P 500 ETF', '대형 혼합', 1, 1),
  ('IVV',  'iShares Core S&P 500 ETF', '대형 혼합', 1, 2),
  ('SPY',  'SPDR S&P 500 ETF Trust', '대형 혼합', 1, 3),
  ('VTI',  'Vanguard Total Stock Market ETF', '대형 혼합', 1, 4),
  ('QQQ',  'Invesco QQQ Trust', '대형 성장', 1, 5),
  ('VEA',  'Vanguard FTSE Developed Markets ETF', '선진국', 1, 6),
  ('VUG',  'Vanguard Growth ETF', '대형 성장', 1, 7),
  ('IEFA', 'iShares Core MSCI EAFE ETF', '선진국', 1, 8),
  ('VTV',  'Vanguard Value ETF', '대형 가치', 1, 9),
  ('GLD',  'SPDR Gold Shares', '원자재', 1, 10),
  ('BND',  'Vanguard Total Bond Market ETF', '채권', 1, 11),
  ('AGG',  'iShares Core US Aggregate Bond ETF', '채권', 1, 12),
  ('IEMG', 'iShares Core MSCI Emerging Markets ETF', '신흥국', 1, 13),
  ('VXUS', 'Vanguard Total Intl Stock ETF', '국제주식', 1, 14),
  ('SPYM', 'SPDR Portfolio S&P 500 ETF', '대형 혼합', 1, 15),
  ('IWF',  'iShares Russell 1000 Growth ETF', '대형 성장', 1, 16),
  ('VWO',  'Vanguard FTSE Emerging Markets ETF', '신흥국', 1, 17),
  ('VGT',  'Vanguard Information Technology ETF', '기술', 1, 18),
  ('IJH',  'iShares Core S&P Mid-Cap ETF', '중형 혼합', 1, 19),
  ('VIG',  'Vanguard Dividend Appreciation ETF', '배당성장', 1, 20),
  ('VO',   'Vanguard Mid-Cap ETF', '중형 혼합', 1, 21),
  ('IJR',  'iShares Core S&P Small-Cap ETF', '소형 혼합', 1, 22),
  ('XLK',  'Technology Select Sector SPDR Fund', '기술', 1, 23),
  ('RSP',  'Invesco S&P 500 Equal Weight ETF', '대형 혼합', 1, 24),
  ('SCHD', 'Schwab US Dividend Equity ETF', '배당', 1, 25),
  ('SGOV', 'iShares 0-3 Month Treasury Bond ETF', '단기채권', 1, 26),
  ('ITOT', 'iShares Core S&P Total US Stock Market ETF', '대형 혼합', 1, 27),
  ('BNDX', 'Vanguard Total Intl Bond ETF', '국제채권', 1, 28),
  ('VYM',  'Vanguard High Dividend Yield ETF', '배당', 1, 29),
  ('IWM',  'iShares Russell 2000 ETF', '소형 혼합', 1, 30);
